sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: WLpTkyvOL690+FTWCKVwfNzyrsO+h3h8F8XQbyJizxJBf/kBqHRMd+lLzN3jqyQjSABZgC2SZoUGiqYqXuQLJSZ6SAl3wx+fKRJDU1bb0QDxd60fytlakk1yMFlsZHPyA8CuKHaIfic0wL7iRbCQVEDWky+94Nh8Xh4IgMvVbYU=
